/**
 * Downloads Clash Display and Satoshi from Fontshare into public/fonts and
 * emits src/styles/fonts.css with local @font-face rules.
 *
 * Self-hosting removes a render-blocking cross-origin stylesheet, an extra DNS
 * + TLS handshake on every cold visit, and a third-party dependency that can
 * (and did) fail intermittently. Run once; re-run only to update the fonts.
 *
 *   node scripts/fetch-fonts.mjs
 */
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

const CSS_URL =
  'https://api.fontshare.com/v2/css?f[]=clash-display@600,700&f[]=satoshi@400,500,700&display=swap'
const OUT_DIR = 'public/fonts'

// Fontshare varies its response by UA; ask as a modern browser to get woff2.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'

await mkdir(OUT_DIR, { recursive: true })

/** Fontshare rate-limits bursts with 5xx, so back off and retry. */
async function fetchWithRetry(url, attempts = 6) {
  let wait = 1500
  for (let i = 1; i <= attempts; i++) {
    try {
      const r = await fetch(url, { headers: { 'user-agent': UA } })
      if (r.ok) return r
      if (i === attempts) throw new Error(`${r.status} after ${attempts} attempts`)
      console.log(`  ${r.status} — retrying in ${wait / 1000}s (${i}/${attempts})`)
    } catch (e) {
      if (i === attempts) throw e
      console.log(`  ${String(e).slice(0, 60)} — retrying in ${wait / 1000}s (${i}/${attempts})`)
    }
    await new Promise((r) => setTimeout(r, wait))
    wait = Math.min(wait * 2, 20_000)
  }
  throw new Error('unreachable')
}

const res = await fetchWithRetry(CSS_URL)
const sourceCss = await res.text()

// Fontshare emits protocol-relative URLs and three formats per face. Every
// browser this site targets supports woff2, so the woff/ttf fallbacks are
// dropped — they would triple the download for no reach.
const faces = [...sourceCss.matchAll(/@font-face\s*\{([\s\S]*?)\}/g)].map((m) => m[1])
if (faces.length === 0) throw new Error('No @font-face blocks in the Fontshare response')

const downloads = new Map()
const rules = []

for (const body of faces) {
  const family = body.match(/font-family:\s*'([^']+)'/)?.[1]
  const weight = body.match(/font-weight:\s*(\d+)/)?.[1] ?? '400'
  const style = body.match(/font-style:\s*(\w+)/)?.[1] ?? 'normal'
  const woff2 = body.match(/url\('(\/\/[^']+?\.woff2)'\)/)?.[1]
  if (!family || !woff2) continue

  const file = `${family.toLowerCase().replace(/\s+/g, '-')}-${weight}.woff2`
  downloads.set(`https:${woff2}`, file)

  rules.push(`@font-face {
  font-family: '${family}';
  src: url('/fonts/${file}') format('woff2');
  font-weight: ${weight};
  font-style: ${style};
  font-display: swap;
}`)
}

console.log(`${downloads.size} woff2 files to fetch\n`)

let total = 0
for (const [url, file] of downloads) {
  const bin = await fetchWithRetry(url)
  const buf = Buffer.from(await bin.arrayBuffer())
  await writeFile(path.join(OUT_DIR, file), buf)
  total += buf.length
  console.log(`✓ ${file} (${(buf.length / 1024).toFixed(1)} KB)`)
}

const css = `/*
 * Self-hosted webfonts — generated by scripts/fetch-fonts.mjs. Do not edit by
 * hand; re-run the script to refresh.
 *
 * Clash Display and Satoshi by Indian Type Foundry, via Fontshare.
 * Licence: free for personal and commercial use
 * https://www.fontshare.com/licenses/itf-ffl
 */

${rules.join('\n\n')}
`

await writeFile('src/styles/fonts.css', css, 'utf8')
console.log(`\n✓ src/styles/fonts.css — ${rules.length} faces, ${(total / 1024).toFixed(1)} KB total`)
