/**
 * Post-build step: derive sitemap.xml and robots.txt from what was actually
 * emitted into dist/, so a new route can never be missing from the sitemap.
 *
 *   node scripts/postbuild.mjs
 */
import { readdir, readFile, writeFile, stat } from 'node:fs/promises'
import path from 'node:path'

const DIST = 'dist'

// Read the canonical origin from the app's own config rather than duplicating it.
const siteSource = await readFile('src/data/site.ts', 'utf8')
const ORIGIN = (siteSource.match(/url:\s*'([^']+)'/)?.[1] ?? 'https://example.com').replace(/\/$/, '')

/** Routes that should never be indexed. /uefn is unlisted and marked noindex. */
const EXCLUDE = new Set(['/404', '/__forms', '/uefn'])

/** Rough importance ranking — home first, then top-level, then detail pages. */
function priorityFor(route) {
  if (route === '/') return '1.0'
  if (['/work', '/ai', '/demos', '/services', '/skills', '/about', '/contact'].includes(route))
    return '0.9'
  if (route === '/blog' || route === '/resume') return '0.8'
  if (route.startsWith('/work/') || route.startsWith('/demos/')) return '0.7'
  if (route.startsWith('/blog/')) return '0.6'
  return '0.5'
}

function changefreqFor(route) {
  if (route === '/' || route === '/blog') return 'weekly'
  if (route.startsWith('/blog/')) return 'yearly'
  return 'monthly'
}

async function walk(dir, acc = []) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) await walk(full, acc)
    else if (entry.name.endsWith('.html')) acc.push(full)
  }
  return acc
}

const files = await walk(DIST)

const routes = files
  .map((f) => {
    const rel = path.relative(DIST, f).replace(/\\/g, '/')
    const route = '/' + rel.replace(/index\.html$/, '').replace(/\.html$/, '')
    return route === '/index' ? '/' : route.replace(/\/$/, '') || '/'
  })
  .filter((r) => !EXCLUDE.has(r))
  .sort((a, b) => (a === '/' ? -1 : b === '/' ? 1 : a.localeCompare(b)))

const lastmod = (await stat(path.join(DIST, 'index.html'))).mtime.toISOString().slice(0, 10)

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${routes
  .map(
    (r) => `  <url>
    <loc>${ORIGIN}${r === '/' ? '/' : r}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreqFor(r)}</changefreq>
    <priority>${priorityFor(r)}</priority>
  </url>`
  )
  .join('\n')}
</urlset>
`

const robots = `# ${ORIGIN}
User-agent: *
Allow: /
Disallow: /__forms.html

Sitemap: ${ORIGIN}/sitemap.xml
`

/**
 * `netlify.toml` lives at the repo root, so a drag-and-drop deploy of `dist/`
 * alone would silently lose every header and redirect in it. `_headers` and
 * `_redirects` are read from the publish directory itself, so emitting them
 * here makes both deploy paths behave identically.
 */
const headers = `# Generated by scripts/postbuild.mjs — mirrors netlify.toml so that
# drag-and-drop deploys of this folder get the same headers as Git deploys.

/*
  X-Frame-Options: SAMEORIGIN
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), interest-cohort=()
  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com; style-src 'self' 'unsafe-inline'; font-src 'self' data:; img-src 'self' data: blob: https:; connect-src 'self' https://www.google-analytics.com https://region1.google-analytics.com; frame-src https://www.youtube-nocookie.com https://calendly.com; form-action 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'self'

/assets/*
  Cache-Control: public, max-age=31536000, immutable

/fonts/*
  Cache-Control: public, max-age=31536000, immutable

/images/*
  Cache-Control: public, max-age=604800, stale-while-revalidate=86400
`

const redirects = `# Generated by scripts/postbuild.mjs
# Every route is prerendered, so this only catches genuinely unknown paths.
/*  /404.html  404
`

await writeFile(path.join(DIST, 'sitemap.xml'), sitemap, 'utf8')
await writeFile(path.join(DIST, 'robots.txt'), robots, 'utf8')
await writeFile(path.join(DIST, '_headers'), headers, 'utf8')
await writeFile(path.join(DIST, '_redirects'), redirects, 'utf8')

console.log(`sitemap.xml — ${routes.length} routes`)
console.log(`robots.txt  — sitemap points at ${ORIGIN}/sitemap.xml`)
console.log(`_headers    — security + cache rules (works on drag-and-drop deploys)`)
console.log(`_redirects  — 404 fallback`)

if (ORIGIN.includes('netlify.app')) {
  console.log(
    `\n  Note: SITE.url in src/data/site.ts is still ${ORIGIN}.\n` +
      `  Update it after pointing a custom domain at the site — canonical URLs,\n` +
      `  OG tags, JSON-LD and this sitemap all derive from it.`
  )
}
